import {test,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
function compile(file){let source=fs.readFileSync(file,'utf8');if(file.includes('route.ts'))source=source.replace("'../../lib/seo'",JSON.stringify(compile('lib/seo.ts')));return 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');}
const seo=await import(compile('lib/seo.ts')),sitemap=await import(compile('app/sitemap.xml/route.ts')),robots=await import(compile('app/robots.txt/route.ts'));
beforeEach(()=>{delete process.env.SEO_INDEXABLE;delete process.env.POLICIES_APPROVED;delete process.env.PUBLIC_SITE_URL;});
test('private launch keeps marketing out of the sitemap and search index',async()=>{assert.equal(seo.pageMetadata('/','Title','Description').robots.index,false);assert.deepEqual(seo.sitemapPaths(),[]);assert.match(await (await robots.GET()).text(),/Disallow: \/\n/);assert.doesNotMatch(await (await sitemap.GET()).text(),/<loc>/);});
test('public sitemap includes marketing but never customer exports, APIs or unapproved policies',async()=>{process.env.SEO_INDEXABLE='1';const xml=await (await sitemap.GET()).text();assert.match(xml,/<loc>https:\/\/parcelexport.com\/csv-guide<\/loc>/);for(const g of seo.guides){assert.match(xml,new RegExp('<loc>https://parcelexport.com'+g.path+'</loc>'));assert.equal(seo.indexable(g.path),true);assert.equal(seo.guideMetadata(g.path).alternates.canonical,'https://parcelexport.com'+g.path);}for(const path of ['/results','/api/jobs','/privacy','/terms','/refunds'])assert.equal(seo.indexable(path),false);assert.doesNotMatch(xml,/results|api\/|privacy|terms|refunds/);assert.match(await (await robots.GET()).text(),/Disallow: \/results/);});
test('approved policies can enter search but results remain noindex with no snippet',()=>{process.env.SEO_INDEXABLE='1';process.env.POLICIES_APPROVED='1';assert.equal(seo.indexable('/privacy'),true);const meta=seo.pageMetadata('/results','Results','Private results');assert.deepEqual(meta.robots,{index:false,follow:false,nosnippet:true});assert.equal(meta.alternates.canonical,'https://parcelexport.com/results');});
test('canonical and share links use one HTTPS origin without credentials, query or fragment',()=>{process.env.PUBLIC_SITE_URL='https://parcel.example/path?export=private#key=secret';const meta=seo.pageMetadata('/pricing','Pricing','Prices');assert.equal(meta.alternates.canonical,'https://parcel.example/pricing');assert.equal(meta.openGraph.url,meta.alternates.canonical);assert.equal(meta.openGraph.images[0].url,'https://parcel.example/social-card.png');process.env.PUBLIC_SITE_URL='https://secret@parcel.example';assert.equal(seo.siteOrigin(),'https://parcelexport.com');process.env.PUBLIC_SITE_URL='http://parcel.example';assert.equal(seo.siteOrigin(),'https://parcelexport.com');});
