'use client';
import {useEffect,useState,useRef} from 'react';
import {Package,Check,Download,Link as LinkIcon,ArrowUpRight,Mail,RefreshCw,ShieldCheck,Clock} from 'lucide-react';
import {exportPresentation,observedETA} from '../lib/export-presentation.mjs';
import {api,checkDownload,recoveryAccess,resultsPath,refreshConfig,subscribeConfig} from '../lib/client-api.mjs';
export default function BackgroundExport({data=null,options={},enabled=true,payments=false,resultsOnly=false,onLockChange}:{data?:any,options?:any,enabled?:boolean,payments?:boolean,resultsOnly?:boolean,onLockChange?:(locked:boolean)=>void}){
 const [access,setAccess]=useState<any>(null),[savedEarlier,setSavedEarlier]=useState<any>(null),[job,setJob]=useState<any>(null),[error,setError]=useState(''),[connectionError,setConnectionError]=useState(''),[connectionStatus,setConnectionStatus]=useState(0),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[copied,setCopied]=useState(false),[config,setConfig]=useState<any>({email:false,stripe:false,paypal:false}),[loaded,setLoaded]=useState(false),[refresh,setRefresh]=useState(0),[downloadURL,setDownloadURL]=useState(''),[notice,setNotice]=useState('');
 const autoDownload=useRef(false),emailInput=useRef<HTMLInputElement>(null),lastProgress=useRef<any>(null);
 const [emailError,setEmailError]=useState(''),[measuredETA,setMeasuredETA]=useState<number|null>(null),[showReturnLink,setShowReturnLink]=useState(false),[downloadExpires,setDownloadExpires]=useState(0);
 useEffect(()=>{if(!job)return;const now=Date.now(),previous=lastProgress.current;setMeasuredETA(observedETA(previous?.job,job,previous?now-previous.time:0));lastProgress.current={job,time:now};},[job]);
 useEffect(()=>{if(!downloadExpires)return;const timer=setTimeout(()=>{setDownloadURL('');setNotice('The direct download link expired. Click Download ZIP for a new link.');},Math.max(0,downloadExpires-Date.now()));return()=>clearTimeout(timer);},[downloadExpires]);
 function remember(a:any){try{localStorage.setItem('parcel-job',JSON.stringify(a));localStorage.setItem('parcel-job:'+a.id,JSON.stringify(a));}catch{setNotice('Browser storage is unavailable. Copy your private return link before leaving.');}}
 useEffect(()=>{onLockChange?.(!!access||busy);},[access,busy,onLockChange]);
 useEffect(()=>{const unsubscribe=subscribeConfig(setConfig);refreshConfig().then((v:any)=>{setConfig(v);}).catch((e:any)=>setConnectionError(e.message));const restore=()=>{const explicit=new URLSearchParams(location.search).has('export')||location.hash.includes('export=');const a=recoveryAccess(location.href,(k:string)=>localStorage.getItem(k));if(a&&(explicit||location.pathname!=='/')){setAccess(a);remember(a);setSavedEarlier(null);}else if(a){setSavedEarlier(a);}else if(explicit)setError('This link is missing its private access key. Paste the complete return link, including the text after #.');setLoaded(true);};restore();window.addEventListener('hashchange',restore);return()=>{unsubscribe();window.removeEventListener('hashchange',restore);};},[]);
 async function reload(a=access){const j=await api('/api/jobs/status?id='+encodeURIComponent(a.id),{headers:{'x-export-key':a.key}});setJob(j);setConnectionError('');setConnectionStatus(0);return j;}
 useEffect(()=>{if(!access)return;let stopped=false,terminal=false;let timer:any;const controller=new AbortController();async function poll(){try{const j=await api('/api/jobs/status?id='+encodeURIComponent(access.id),{headers:{'x-export-key':access.key},signal:AbortSignal.any([controller.signal,AbortSignal.timeout(30000)])});if(!stopped){setJob(j);setConnectionError('');setConnectionStatus(0);}}catch(e:any){if(!stopped){setConnectionError(e.message);setConnectionStatus(e.status||0);terminal=[403,404,410].includes(e.status);if(terminal)setJob(null);}}finally{if(!stopped&&!terminal)timer=setTimeout(poll,5000);}}poll();return()=>{stopped=true;controller.abort();clearTimeout(timer);};},[access,refresh]);
 async function action(type:string,details:any={},a=access){return api('/api/jobs/action',{method:'POST',headers:{'Content-Type':'application/json','x-export-key':a.key},body:JSON.stringify({id:a.id,action:type,...details})});}
 async function start(){if(!data||!enabled||access||busy||data.products>25&&!payments)return;if(config.email&&email.trim()&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())){setEmailError('Enter a valid email address or leave it blank.');emailInput.current?.focus();return;}setBusy(true);setError('');try{let pending;try{pending=JSON.parse(sessionStorage.getItem('parcel-job-attempt')||'null');}catch{}const fingerprint=JSON.stringify({items:data.images,options,email});if(pending?.fingerprint!==fingerprint)pending=null;if(!pending)pending={fingerprint,attempt:crypto.randomUUID(),key:Array.from(crypto.getRandomValues(new Uint8Array(32))).map(v=>v.toString(16).padStart(2,'0')).join('')};try{sessionStorage.setItem('parcel-job-attempt',JSON.stringify(pending));}catch{}const j=await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:data.images,options,email:config.email?email.trim()||undefined:undefined,attempt:pending.attempt,key:pending.key})});const a={id:j.id,key:pending.key};remember(a);try{sessionStorage.removeItem('parcel-job-attempt');}catch{}setAccess(a);setJob(j);setCopied(false);history.replaceState(null,'',location.pathname+'?export='+a.id+'#key='+a.key);autoDownload.current=false;}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function doAction(type:string){setBusy(true);setError('');try{await action(type);await reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function download(){setBusy(true);setError('');setDownloadURL('');try{const v=await action('download');if(v.preparing){setNotice('We are combining your saved images into one ZIP. No need to upload again.');await reload();return;}if(!v.url)throw Error('No download link was returned. Please retry.');await checkDownload(v.url);setDownloadURL(v.url);setDownloadExpires(Date.now()+(v.expiresInSeconds||3600)*1000);const a=document.createElement('a');a.href=v.url;a.download='parcel-'+access.id+'.zip';document.body.appendChild(a);a.click();a.remove();setNotice('Your ZIP download was requested. If it did not start, use the direct link in the package panel.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function pay(provider:string){setBusy(true);setError('');try{remember(access);try{sessionStorage.setItem('parcel-pending-download',JSON.stringify({id:job.id}));}catch{}const v=await action('checkout',{provider});if(v.url)location.assign(v.url);else if(v.paid){await action('confirm');await reload();}else throw Error('Checkout did not return a payment page. Please retry.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{if(!job||!access||autoDownload.current||!job.paid||!['complete','partial'].includes(job.state))return;try{const pending=JSON.parse(sessionStorage.getItem('parcel-pending-download')||'null');if(pending?.id===job.id){autoDownload.current=true;sessionStorage.removeItem('parcel-pending-download');download();}}catch{}},[job,access]);
 useEffect(()=>{if(!access)return;const params=new URLSearchParams(location.search);if(params.has('session_id')||params.has('token'))action('confirm').then(()=>reload()).catch((e:any)=>setError(e.message));if(params.has('cancelled'))setNotice('Checkout was cancelled. Your package is saved; you can return to payment below.');},[access]);
 const processing=job&&['queued','downloading','packing','awaiting_payment'].includes(job.state),ready=job&&['complete','partial'].includes(job.state),available=enabled&&config.background!==false;
 const {packing,title,percent}=exportPresentation(job);
 return <div className="background-export parcel-workflow">
 {savedEarlier&&!access&&<p className="notice saved-earlier">You have a saved export from earlier. <a href={resultsPath(savedEarlier)}>View it</a></p>}
 {available&&data&&!access&&<div className="delivery-setup"><div className="workflow-heading"><Mail size={22}/><div><h3>Prepare your package</h3><p>One ZIP, with every saved image inside.</p></div></div>{config.email&&<><label className="email-field" htmlFor="export-email">Email for your results <span>Optional</span><input ref={emailInput} id="export-email" type="email" autoComplete="email" inputMode="email" autoCapitalize="none" spellCheck={false} maxLength={254} value={email} onChange={e=>{setEmail(e.target.value);setEmailError('');}} placeholder="you@example.com" disabled={busy} aria-invalid={!!emailError} aria-describedby={emailError?'email-help email-error':'email-help'}/></label>{emailError&&<p id="email-error" className="field-error" role="alert">{emailError}</p>}<p id="email-help" className="workflow-note">We’ll email your results when processing finishes. No marketing emails.</p></>}{!config.email&&<p className="workflow-note">You’ll get a private return link after starting. Save it to come back later; email delivery is not available yet.</p>}<button className="primary" disabled={busy||data.products>25&&!payments} onClick={start}>{busy?'Creating your export…':'Prepare my ZIP'} <ArrowUpRight size={18}/></button>{data.products>25&&!payments?<p className="notice">Paid exports are not available yet. The free pilot supports up to 25 products.</p>:<p className="workflow-note">{data.products>25?'Review your package, then pay once to download.':'Up to 25 products · free · no payment required'}</p>}</div>}
 {access&&!job&&!connectionError&&<div className="job-loading" role="status"><Package size={24}/><h3>Finding your saved export</h3><p>Your private link identifies this package.</p></div>}
 {resultsOnly&&!access&&loaded&&!data&&!error&&<div className="job-empty"><Package size={32}/><h3>Open your private return link</h3><p>This page needs the link created with your export. Paste the complete link in your address bar, or prepare a new package.</p><a className="primary" href="/#exporter">Prepare an export <ArrowUpRight size={18}/></a></div>}
 {job&&<section className="job-status job-panel" aria-label="Export status"><div className="workflow-heading"><span className={'job-icon '+(ready?'is-ready':'')}>{ready?<Check size={24}/>:<Package size={24}/>}</span><div><span className="status-eyebrow">{ready?'READY TO DOWNLOAD':processing?'EXPORT IN PROGRESS':'SAVED EXPORT'}</span><h3>{title}</h3></div></div><p className="job-reference">Export {job.id.slice(0,8)}</p><ol className="job-steps" aria-label="Export stages"><li className="done">CSV received</li><li className={ready?'done':'current'}>Prepare ZIP</li><li className={ready?'current':''}>Download</li></ol><div className="job-metrics"><div><strong>{job.completed}<small> / {job.total}</small></strong><span>images saved</span></div><div><strong>{(job.bytes/1000000).toFixed(1)}<small> MB</small></strong><span>original images</span></div><div><strong>1<small> ZIP</small></strong><span>one download</span></div></div>{processing&&<div className="job-progress"><div><span>{title}</span><strong>{percent}%</strong></div><progress aria-label="Package progress" value={percent} max={100}/><p><Clock size={15}/>{packing?'Images checked. Building the archive…':job.state==='queued'?'Waiting for a worker. You can leave this page.':measuredETA?'About '+Math.max(1,Math.ceil(measuredETA/60))+' min to check remaining images, then ZIP packing · based on recent progress':'Estimating time as images are saved. You can leave this page.'}</p></div>}{job.failed>0&&<p className="notice">{job.failed} images could not be saved. {ready?'The ZIP includes a failed-downloads.csv report.':'Review the results below for retry options.'}</p>}{job.lastError&&<p className="notice">{job.lastError}</p>}
 {ready&&job.parts?.length>0&&<div className="package-download"><div className="package-file"><Package size={25}/><div><strong>parcel-{job.id.slice(0,8)}.zip</strong><span>{job.completed} images · {(job.parts[0].bytes/1000000).toFixed(1)} MB · {job.amount?'$'+(job.amount/100).toFixed(2)+' USD':'Free export'}</span></div></div>{job.amount>0&&!job.paid?<><p>One payment unlocks your complete ZIP and repeat downloads until expiry.</p>{(config.stripe||job.paymentProvider==='stripe')&&job.paymentProvider!=='paypal'&&<button className="primary" disabled={busy} onClick={()=>pay('stripe')}>{busy?'Opening checkout…':'Continue to payment · $'+(job.amount/100).toFixed(2)}<ArrowUpRight size={18}/></button>}{(config.paypal||job.paymentProvider==='paypal')&&job.paymentProvider!=='stripe'&&<button className="secondary" disabled={busy} onClick={()=>pay('paypal')}>Pay with PayPal</button>}{!config.stripe&&!config.paypal&&!job.paymentProvider&&<p className="notice">Payments are not configured yet. Checkout is unavailable; your saved link remains valid until expiry.</p>}<p className="workflow-note">Card and eligible Apple Pay through checkout. By paying, you accept the <a href="/terms">terms</a> and <a href="/refunds">no-refund policy</a>.</p></>:<><button className="primary" disabled={busy||!!job.refundState} onClick={download}><Download size={18}/>{busy?'Preparing download…':'Download ZIP'+(job.amount?'':' · free')}</button><p className="workflow-note">{job.paid?'Payment confirmed. No additional payment for this package.':'This export is within the free tier. No checkout is needed.'}</p></>}{downloadURL&&<a className="download-fallback" href={downloadURL} download>Download did not start? Open the ZIP link ↗</a>}</div>}
 <div className="return-panel"><div className="workflow-heading"><ShieldCheck size={19}/><div><h4>Keep your private return link</h4><p>{job.readyAt?'Available until '+new Date(job.expires).toLocaleString():'You can leave this page. Your export continues in the background.'}</p></div></div><div className="return-actions"><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+resultsPath(access));setCopied(true);}catch{setShowReturnLink(true);setNotice('Copy the private link from the field below.');}}}><LinkIcon size={16}/>{copied?'Link copied':'Copy return link'}</button>{!resultsOnly&&<a className="secondary" href={resultsPath(access)}>View results <ArrowUpRight size={16}/></a>}</div><button className="show-link" aria-expanded={showReturnLink} onClick={()=>setShowReturnLink(!showReturnLink)}>{showReturnLink?'Hide private link':'Show private link'}</button>{showReturnLink&&<input className="recovery-link" aria-label="Private return link" readOnly value={typeof window!=='undefined'?location.origin+resultsPath(access):''} onFocus={e=>e.target.select()}/>}<p className="workflow-note">{job.emailState==='sent'?'Results email accepted by the provider.':job.emailState==='failed'?'Email delivery failed. Use this return link.':job.emailState&&!config.email?'Email address saved. Delivery is not enabled yet; use this return link.':job.emailState?'We’ll email your export outcome when processing finishes.':'No email requested. This link is your way back.'} Keep it private.</p></div>
 <div className="job-secondary-actions">{processing&&<button disabled={busy} onClick={()=>doAction('cancel')}>Cancel export</button>}{['failed','partial'].includes(job.state)&&!job.refundState&&job.retries<2&&(!job.paymentProvider||job.paid)&&<button disabled={busy} onClick={()=>doAction('retry')}>Retry failed images</button>}{job.paid&&['failed','partial','cancelled'].includes(job.state)&&<button disabled={busy} onClick={()=>doAction('review')}>Report billing issue</button>}</div>{job.reviewId&&<p>Review reference: {job.reviewId}</p>}{job.refundState&&<p>Refund status: {job.refundState}</p>}</section>}
 {!loaded&&<p role="status">Checking for a saved export…</p>}{notice&&<p className="notice" role="status">{notice}</p>}{error&&<div className="error" role="alert"><p>{error}</p>{resultsOnly&&!access&&<a className="secondary" href="/#exporter">Prepare a new export</a>}</div>}{connectionError&&<div className="error" role="alert"><h3>{connectionStatus===410?'This export has expired':connectionStatus===404?'Export not found':access?'We couldn’t open your export':'Connection unavailable'}</h3><p>{connectionError}</p>{![404,410].includes(connectionStatus)&&<button className="secondary" onClick={()=>{setRefresh(n=>n+1);refreshConfig().then((v:any)=>{setConfig(v);if(!access)setConnectionError('');}).catch((e:any)=>setConnectionError(e.message));}}><RefreshCw size={16}/> Retry connection</button>}</div>}
 {access&&(!job||!processing)&&<button className="new-export" disabled={busy} onClick={()=>{if(!window.confirm('Save your private return link before starting another export. Continue?'))return;try{localStorage.removeItem('parcel-job');}catch{setError('Browser storage could not be cleared. Copy your return link, then retry in a new browser session.');return;}history.replaceState(null,'','/#exporter');location.reload();}}>Start a new export <ArrowUpRight size={16}/></button>}
 </div>;
}
