'use client';
import {useEffect,useRef,useState} from 'react';
import BackgroundExport from './BackgroundExport';
import CsvGuide from './CsvGuide';
import {api,refreshConfig,subscribeConfig} from '../lib/client-api.mjs';
import {Menu,ArrowUpRight,ArrowRight,Upload,Package,FileText,Folder,Check,Download,ShieldCheck,X,ChevronDown,Image as ImageIcon} from 'lucide-react';
import {parseCSV,filename} from '../lib/export.mjs';
export default function Home(){
 const menuButton=useRef<HTMLButtonElement>(null),input=useRef<HTMLInputElement>(null);const [data,setData]=useState<any>(null),[file,setFile]=useState(''),[mode,setMode]=useState('sku'),[folders,setFolders]=useState(true),[manifest,setManifest]=useState(true),[error,setError]=useState(''),[payments,setPayments]=useState(false),[background,setBackground]=useState(false),[configLoaded,setConfigLoaded]=useState(false),[savedOpen,setSavedOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[drag,setDrag]=useState(false);
 useEffect(()=>{const unsubscribe=subscribeConfig((v:any)=>{setPayments(v.payments);setBackground(v.background);setConfigLoaded(true);});refreshConfig().catch((e:any)=>setError(e.message)).finally(()=>setConfigLoaded(true));return unsubscribe;},[]);
 useEffect(()=>{if(data||savedOpen)document.getElementById('exporter')?.scrollIntoView({block:'start',behavior:'auto'});},[!!data,savedOpen]);
 async function upload(f:File){if(savedOpen)return;setError('');if(!f.name.toLowerCase().endsWith('.csv')){setError('Choose a .csv file exported from Shopify Products.');return;}if(f.size>10000000){setError('CSV exceeds the 10 MB limit. Split it into smaller exports.');return;}try{const d=parseCSV(await f.text());if(d.images.length>10000)throw Error('Maximum 10,000 images per export. Split your CSV into smaller files.');setData(d);setFile(f.name);}catch(e:any){setError(e.message);}}
 async function sample(large=false){setError('');try{const r=await fetch(large?'/sample-shopify-products.csv':'/sample-quick.csv');if(!r.ok)throw Error('Sample CSV is temporarily unavailable.');await upload(new File([await r.text()],large?'sample-shopify-products.csv':'sample-quick.csv',{type:'text/csv'}));}catch(e:any){setError(e.message);}}
 
 return <><header className="nav"><a className="brand" href="/"><span className="brandmark"><Package size={23}/></span>parcel<span className="brand-dot">.</span></a><button ref={menuButton} className="menu-toggle" aria-label={menuOpen?'Close navigation':'Open navigation'} aria-expanded={menuOpen} aria-controls="main-navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={22}/>:<Menu size={22}/>}</button><nav id="main-navigation" className="nav-links" data-open={menuOpen} aria-label="Main navigation" onClick={()=>setMenuOpen(false)} onKeyDown={e=>{if(e.key==='Escape'){setMenuOpen(false);menuButton.current?.focus();}}}><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="/csv-guide">CSV guide</a><a className="nav-cta" href="#exporter">Export your images <ArrowUpRight size={16}/></a></nav></header>
 <main id="main-content"><section className={'hero'+(data||savedOpen?' workflow-active':'')}><div className="hero-copy"><div className="eyebrow"><span/> THE SIMPLE SHOPIFY IMAGE EXPORTER</div><h1>Your Shopify images.<br/>All packed up<span className="green">.</span></h1><p className="lede">One CSV in. One organized ZIP out.<br/>Download, rename, and organize your Shopify product images in a few clicks.</p><div className="hero-tags"><span><Check size={15}/> No store login</span><span><Check size={15}/> No image resizing</span><span><Check size={15}/> No subscription</span></div><div className="mini-proof"><span className="mini-icon"><ShieldCheck size={20}/></span><div><strong>Your store stays yours.</strong><p>No app installation. No Shopify permissions.</p></div></div></div>
 <div id="exporter" className="export-card"><div className="card-top"><span><span className="live-dot"/> READY WHEN YOU ARE</span><span>CSV → ZIP</span></div><div className="card-inner"><h2>{savedOpen?'Your saved export':data?'Make it your export.':'Let’s pack your images.'}</h2><p className="muted">{savedOpen?'Your saved package and return link are below.':data?'Choose filenames and folders, then prepare your package.':'Start with your Shopify product CSV.'}</p><input ref={input} aria-label="Upload a Shopify product CSV" type="file" accept=".csv,text/csv" hidden onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])} disabled={savedOpen}/>
 {!savedOpen&&<>{!data?<><button className={'dropzone '+(drag?'drag':'')} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(e.dataTransfer.files[0])upload(e.dataTransfer.files[0]);}}><span className="upload-icon"><Upload size={26}/></span><strong>Drop your product CSV here</strong><span>or click to browse files</span><small>.CSV files · up to 10 MB</small></button><button className="primary" onClick={()=>input.current?.click()}>Upload Shopify CSV <ArrowRight size={18}/></button><button className="sample" onClick={()=>sample()}>Try a quick sample · 3 images <ArrowUpRight size={14}/></button></>:<><div className="file-line"><FileText size={20}/><span>{file}</span><button aria-label="Choose another CSV" disabled={savedOpen} onClick={()=>{setData(null);setError('');if(input.current)input.current.value='';}}> <X size={16}/></button></div><div className="stats"><div><b>{data.products.toLocaleString()}</b><span>products</span></div><div><b>{data.variants.toLocaleString()}</b><span>variant rows</span></div><div><b>{data.images.length.toLocaleString()}</b><span>images</span></div></div>{data.invalid>0&&<p className="notice">{data.invalid} unsupported URLs skipped. Only cdn.shopify.com is accepted.</p>}<div className="options"><label>Filename <select value={mode} disabled={savedOpen} onChange={e=>setMode(e.target.value)}><option value="sku">SKU (handle if missing)</option><option value="handle">Product handle</option><option value="original">Original filename</option></select></label><label>Organization <select value={folders?'folders':'single'} disabled={savedOpen} onChange={e=>setFolders(e.target.value==='folders')}><option value="folders">Folder per product</option><option value="single">Single folder</option></select></label><label className="checkbox"><input type="checkbox" checked={manifest} disabled={savedOpen} onChange={e=>setManifest(e.target.checked)}/> Include image details spreadsheet (manifest.csv)</label></div><div className="path-preview"><Folder size={15}/><code>{filename(data.images[0],1,mode,folders,new Set(),'jpg')}</code></div>{configLoaded&&!background&&<p className="notice">Background processing is temporarily unavailable. Retry the connection before preparing your ZIP. <button className="secondary" onClick={()=>refreshConfig().catch((e:any)=>setError(e.message))}>Retry connection</button></p>}{!configLoaded&&<p role="status">Checking export availability…</p>}</>}</>}
 <BackgroundExport data={data} options={{mode,folders,manifest}} enabled={configLoaded&&background} payments={payments} onLockChange={setSavedOpen}/>{error&&<div className="error" role="alert">{error}</div>}<div className="sample-links"><a href="/sample-quick.csv" download><Download size={13}/> Download sample CSV</a>{!savedOpen&&!data&&<button className="text-link" onClick={()=>sample(true)}>Large sample · 50 images</button>}<a href="#csv-guide">CSV format guide <ArrowUpRight size={13}/></a></div><div className="card-foot"><ShieldCheck size={14}/> Your CSV is parsed in your browser.</div></div></div></section>
 <section className="benefit-strip"><div><Folder size={22}/><span>Every product.<br/><strong>In its own place.</strong></span></div><div><ImageIcon size={22}/><span>Original image files.<br/><strong>Nothing resized.</strong></span></div><div><FileText size={22}/><span>URLs, SKUs, alt text.<br/><strong>Image details included.</strong></span></div><div><Package size={22}/><span>Your first 25 products.<br/><strong>On the house.</strong></span></div></section>
 <section id="how" className="how"><div className="section-title"><div><span className="eyebrow">LESS CLICKING. MORE DOING.</span><h2>From store to folder in three steps.</h2></div></div><div className="steps"><article><span className="number">01</span><h3>Export your products</h3><p>In Shopify, open Products → Export. Choose your products and export as a CSV.</p><div className="step-pill"><FileText size={14}/> products_export.csv</div></article><article><span className="number">02</span><h3>Give every image a home</h3><p>Upload your CSV. Choose SKU or handle filenames, and a folder for each product.</p><div className="step-pill"><Folder size={14}/> SKU-01-1.jpg</div></article><article><span className="number">03</span><h3>Take the whole collection</h3><p>Download a ZIP with your images and an image details spreadsheet. Failed downloads get their own report.</p><div className="step-pill"><Download size={14}/> shopify-image-export.zip</div></article></div></section>
 <section className="example"><div><span className="eyebrow">ORDER, DELIVERED.</span><h2>A little less chaos.<br/>A lot more organization.</h2><p>Ready for a migration, a catalog refresh, or a simple image backup. Every file has a name. Every product has a place.</p><a href="#exporter" className="text-link">Pack your first export <ArrowRight size={17}/></a></div><div className="folder-window"><div className="window-bar"><span><i/><i/><i/></span><small>Example ZIP structure</small></div><div className="folder-body"><p><Package size={17}/> <b>shopify-image-export.zip</b></p><div className="tree"><p><Folder size={16}/> canvas-tote/</p><span><ImageIcon size={14}/> TOTE-01-1.jpg</span><span><ImageIcon size={14}/> TOTE-01-2.jpg</span><p><Folder size={16}/> ceramic-mug/</p><span><ImageIcon size={14}/> MUG-01-1.jpg</span><p><FileText size={16}/> manifest.csv <em>the details, too</em></p></div></div></div></section>
 <section id="pricing" className="pricing"><span className="eyebrow">PAY PER EXPORT. THAT’S IT.</span><h2>A small price for a big time-saver.</h2><p>Start free. Larger exports will use a one-time payment.</p><div className="prices">{[['Try it out','Up to 25 products','$0','Available now'],['Small catalog','26–250 products','$9','Coming soon'],['Growing store','251–1,000 products','$19','Coming soon'],['Full collection','Over 1,000 products','$39','Coming soon']].map((p,n)=><article key={p[0]} className={n===0?'free':''}><span>{p[0]}</span><b>{p[2]}</b><p>{p[1]}</p><small>{n===0?p[3]:payments?'Available':p[3]}</small></article>)}</div><p className="limits">Up to 10,000 images per export · 20 MB per image · Every export is delivered as one ZIP containing your images and reports. Background exports are available when the worker is connected. Limits: 300 MB free, 1 GB paid; 5 jobs per client per day and 2 active jobs. Files are retained for 24 hours.</p></section>
 <CsvGuide/>
 <section className="faq"><h2>A few things you might be wondering.</h2>{[['Do I need to connect my Shopify store?','No. Export your product CSV from Shopify and upload it here. Parcel never asks for your store password, an API token, or Shopify permissions.'],['Are images compressed or resized?','No. The exporter downloads the exact image files at the URLs in your CSV. If a URL points to a resized version, that is the version included.'],['What happens if an image fails?','The export continues with the remaining images. A failed-downloads.csv file lists unsuccessful URLs and their errors. If every image fails, you receive an error instead of an empty ZIP.'],['Where is my CSV stored?','CSV parsing happens locally. Saved exports store image metadata, images and your ZIP on the server with access expiring 24 hours after the package becomes ready. The worker deletes stored files after expiry; deletion can be delayed if it is unavailable. Payment and error records are kept separately for recovery and review.'],['How many files do I download?','One ZIP per export. It contains your product folders, original image files, the optional image details spreadsheet, and a failed-download report if needed. Older saved exports are combined into one ZIP when you request a download.'],['Are purchases refundable?','Completed purchases are final; we do not offer discretionary refunds. Review your prepared results and price before paying. Billing errors and exceptions required by applicable law are handled under the no-refund policy linked below.'],['Can I close the tab during an export?','After choosing Prepare package, save the private return link shown with your progress. Processing continues after you close the tab. If email is enabled, enter your address before preparing the package. Results stay available for 24 hours after they are ready. If the worker is unavailable, saved progress is retained until it reconnects or the export expires.'],['Which images are supported?','HTTPS images hosted on cdn.shopify.com in JPEG, PNG, WebP, GIF, or AVIF format. Other hosts are skipped. Duplicate image URLs within a product are downloaded once.']].map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</section>
 </main><footer><a className="brand" href="/">parcel<span className="brand-dot">.</span></a><span>Less busywork. More store.</span><nav className="footer-links" aria-label="Information pages"><a href="/pricing">Pricing</a><a href="/support">Support</a><a href="/refunds">Refunds</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav><small>© 2026 Lumen Collectives LLC · Independent tool. Not affiliated with Shopify.</small></footer></>;
}
