import {db,HttpError} from './guard';
const enc=new TextEncoder();
async function key(use:string){if(!process.env.EXPORT_SIGNING_SECRET)throw new HttpError(503,'Secure links unavailable.');return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(use+process.env.EXPORT_SIGNING_SECRET)),use==='encrypt'?{name:'AES-GCM'}:{name:'HMAC',hash:'SHA-256'},false,use==='encrypt'?['encrypt','decrypt']:['sign','verify']);}
function b64(b:Uint8Array){return btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
function unb64(s:string){return Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));}
export async function seal(value:any){const iv=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key('encrypt'),enc.encode(JSON.stringify(value)));return b64(iv)+'.'+b64(new Uint8Array(ciphertext));}
export async function open(value:string){const [iv,data]=value.split('.');return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv)},await key('encrypt'),unb64(data))));}
export async function downloadLink(job:any,part:number,origin:string){if(!['complete','partial'].includes(job.state)||!job.parts)throw new HttpError(409,'Your package is not ready.');if(job.amount&&!job.payment_intent)throw new HttpError(402,'Payment is required before download.');if(job.refund_state)throw new HttpError(409,'Download unavailable while payment is under refund review.');const exists=await db().prepare('SELECT part FROM export_parts WHERE job_id=? AND part=?').bind(job.id,part).first();if(!exists)throw new HttpError(404,'ZIP part not found.');const now=Date.now(),expires=Math.min(job.expires,now+3600000);if(expires<=now)throw new HttpError(410,'This export has expired.');const payload=b64(enc.encode(JSON.stringify({id:job.id,part,exp:expires})));const sig=b64(new Uint8Array(await crypto.subtle.sign('HMAC',await key('download'),enc.encode(payload))));return {url:origin+'/api/jobs/download?token='+payload+'.'+sig,expiresInSeconds:Math.floor((expires-now)/1000)};}
export async function downloadAccess(token:string){try{if(token.length>1000)throw Error();const [payload,sig]=token.split('.');if(!payload||!sig||!await crypto.subtle.verify('HMAC',await key('download'),unb64(sig),enc.encode(payload)))throw Error();const p=JSON.parse(new TextDecoder().decode(unb64(payload)));if(!Number.isInteger(p.part)||p.part<1||!Number.isFinite(p.exp)||p.exp<=Date.now())throw Error();const job:any=await db().prepare('SELECT * FROM exports WHERE id=?').bind(p.id).first();if(!job||job.expires<=Date.now()||!['complete','partial'].includes(job.state)||job.amount&&!job.payment_intent||job.refund_state)throw Error();return {job,part:p.part};}catch{throw new HttpError(403,'Download link expired or invalid. Return to your results page for a new link.');}}
