export function parseCSV(text){
 const rows=[];let row=[],cell='',quoted=false;
 text=text.replace(/^\uFEFF/,'');
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++;}else quoted=false;}else cell+=c;}else if(c==='"'){if(cell)throw Error('Malformed CSV: unexpected quote.');quoted=true;}else if(c===','){row.push(cell);cell='';}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}
 if(quoted)throw Error('Malformed CSV: unclosed quote.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);
 const aliases={'URL handle':'Handle','Product image URL':'Image Src','Image position':'Image Position','Image alt text':'Image Alt Text','Variant image URL':'Variant Image','SKU':'Variant SKU','Option1 value':'Option1 Value'};const headers=rows.shift()?.map(s=>Object.hasOwn(aliases,s.trim())?aliases[s.trim()]:s.trim())||[];if(!headers.includes('Handle')||(!headers.includes('Image Src')&&!headers.includes('Variant Image')))throw Error('Use a Shopify product CSV with Handle (or URL handle) and Image Src (or Product image URL / Variant image URL).');
 const products=new Map();let last='';const images=[];let variants=0;const seen=new Set();let invalid=0;
 for(const cells of rows){if(cells.length>headers.length)throw Error('Malformed CSV: a row has more fields than the header.');const r=Object.fromEntries(headers.map((h,i)=>[h,cells[i]?.trim()||'']));const handle=r.Handle||last;if(!handle)continue;last=handle;let p=products.get(handle);if(!p){p={handle,title:handle,sku:''};products.set(handle,p);}if(r.Title)p.title=r.Title;if(r['Variant SKU']&&!p.sku)p.sku=r['Variant SKU'];if(r['Variant SKU']||r['Option1 Value'])variants++;
 for(const url of [r['Image Src'],r['Variant Image']]){if(!url)continue;const k=handle+'\0'+url;if(seen.has(k))continue;seen.add(k);if(!safeURL(url)){invalid++;continue;}images.push({url,handle,title:'',sku:r['Variant SKU']||'',position:Number(r['Image Position'])||0,alt:r['Image Alt Text']||''});}}
 images.forEach((i)=>{const p=products.get(i.handle);i.title=p.title;i.sku=i.sku||p.sku;});images.sort((a,b)=>a.handle.localeCompare(b.handle)||a.position-b.position);
 if(!images.length)throw Error(invalid?'No supported images found. This version accepts HTTPS images on cdn.shopify.com.':'No image URLs found in this CSV.');
 return {products:new Set(images.map(i=>i.handle)).size,catalogProducts:products.size,variants,images,invalid};
}
export function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='cdn.shopify.com'&&!u.username&&!u.password&&(!u.port||u.port==='443');}catch{return false;}}
export function sanitize(value){return String(value).normalize('NFKC').replace(/[\u0000-\u001f\u007f/\\:*?"<>|]/g,'-').replace(/[^\p{L}\p{N}._-]+/gu,'-').replace(/^[. -]+|[. -]+$/g,'').slice(0,90)||'image';}
export function filename(image,index,mode,folders,used,extension){let original;try{original=decodeURIComponent(new URL(image.url).pathname.split('/').pop()||'image').replace(/\.[^.]+$/,'');}catch{original='image';}let base=sanitize(mode==='original'?original:mode==='sku'?image.sku||image.handle:image.handle);if(mode!=='original')base+='-'+index;let prefix=folders?sanitize(image.handle)+'/':'';let name=prefix+base+'.'+extension,n=2;while(used.has(name.toLowerCase()))name=prefix+base+'-'+n++ +'.'+extension;used.add(name.toLowerCase());return name;}
export function csv(rows){return rows.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');}
export function price(n){return n<=25?0:n<=250?900:n<=1000?1900:3900;}
const table=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
export function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
export function zipWriter(write,state={}){let offset=state.offset||0;const entries=(state.entries||[]).map(e=>({...e,n:Uint8Array.from(e.n)}));const enc=new TextEncoder();const emit=async b=>{await write(b);offset+=b.length;};return {snapshot(){return {offset,entries:entries.map(e=>({...e,n:Array.from(e.n)}))};},async add(name,data){const n=enc.encode(name),crc=crc32(data),h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,33,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,n.length,true);h.set(n,30);entries.push({n,crc,size:data.length,offset});await emit(h);await emit(data);},async close(){const start=offset;for(const e of entries){const h=new Uint8Array(46+e.n.length),v=new DataView(h.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x800,true);v.setUint16(14,33,true);v.setUint32(16,e.crc,true);v.setUint32(20,e.size,true);v.setUint32(24,e.size,true);v.setUint16(28,e.n.length,true);v.setUint32(42,e.offset,true);h.set(e.n,46);await emit(h);}const h=new Uint8Array(22),v=new DataView(h.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,offset-start,true);v.setUint32(16,start,true);await emit(h);}};}
export function zipParts({limit=128000000,reserve=12000000,includeManifest=true,onPart}){let chunks=[],size=0,part=1,count=0,rows=[],zip;const enc=new TextEncoder(),header=['product_title','handle','sku','image_position','original_url','filename','alt_text'];
 const begin=()=>{chunks=[];size=0;count=0;rows=[];zip=zipWriter(async b=>{if(size+b.length>limit)throw Error('A ZIP part exceeds this browser’s size limit. Split your CSV into smaller exports.');chunks.push(b);size+=b.length;});};
 const finish=async(failures=[])=>{if(includeManifest)await zip.add('manifest.csv',enc.encode(csv([header,...rows])));if(failures.length)await zip.add('failed-downloads.csv',enc.encode(csv([['handle','original_url','error'],...failures])));await zip.close();await onPart({part,bytes:size,chunks,images:count});part++;begin();};begin();return {async add(name,data,row){if(count&&size+data.length+enc.encode(name).length+reserve>limit)await finish();await zip.add(name,data);rows.push(row);count++;},async close(failures=[]){if(count||failures.length)await finish(failures);}};}
