import {env} from 'cloudflare:workers';
export function db(){if(!env.DB)throw new HttpError(503,'Storage is not configured.');return env.DB;}
export function bucket(){if(!env.BUCKET)throw new HttpError(503,'File storage is not configured.');return env.BUCKET;}
export class HttpError extends Error{constructor(public status:number,message:string,public retryAfter=0){super(message);}}
export async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function client(request:Request){return hash((process.env.EXPORT_SIGNING_SECRET||'')+'|'+(request.headers.get('cf-connecting-ip')||request.headers.get('oai-authenticated-user-id')||'unknown'));}
export async function boundedJSON(request:Request,limit=2000000){if(Number(request.headers.get('content-length'))>limit)throw new HttpError(413,'CSV metadata is too large. Split this export.');const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'Request body required.');let size=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>limit){await reader.cancel();throw new HttpError(413,'CSV metadata is too large. Split this export.');}chunks.push(value);}const bytes=new Uint8Array(size);let n=0;for(const c of chunks){bytes.set(c,n);n+=c.length;}try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw new HttpError(400,'Invalid JSON.');}}
export async function consume(id:string,amount:number,limit:number,expires:number){if(amount>limit||amount<0)throw new HttpError(429,'Usage limit reached.',60);const result=await db().prepare('INSERT INTO usage_limits (id,value,expires) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET value=value+excluded.value WHERE value+excluded.value<=? RETURNING value').bind(id,amount,expires,limit).first();if(!result)throw new HttpError(429,'Usage limit reached. Try again after the limit resets.',Math.max(1,Math.ceil((expires-Date.now())/1000)));}
export async function rate(request:Request,scope:string,limit:number,window=3600000){const t=Date.now(),ip=await client(request),start=Math.floor(t/window)*window;await consume('rate:'+scope+':'+ip+':'+start,1,limit,start+window);}
export async function reserveTransfer(ip:string,amount:number){const now=Date.now(),start=Math.floor(now/86400000)*86400000,expires=start+86400000;const ids=['bytes:global:'+start,'bytes:'+ip+':'+start];await consume(ids[0],amount,Number(process.env.GLOBAL_DAILY_BYTES)||5000000000,expires);try{await consume(ids[1],amount,Number(process.env.CLIENT_DAILY_BYTES)||1000000000,expires);}catch(e){await db().prepare('UPDATE usage_limits SET value=MAX(0,value-?) WHERE id=?').bind(amount,ids[0]).run();throw e;}return async(actual:number)=>{await db().batch(ids.map(id=>db().prepare('UPDATE usage_limits SET value=MAX(0,value-?) WHERE id=?').bind(Math.max(0,amount-actual),id)));};}
export async function event(code:string,detail:string,jobId?:string){console.error(JSON.stringify({event:code,jobId:jobId||null}));try{const day=Math.floor(Date.now()/86400000)*86400000;await consume('error-events:'+day,1,1000,day+86400000);await db().prepare('INSERT INTO error_events(id,job_id,code,detail,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),jobId||null,code,detail.replace(/https?:\/\/\S+/g,'[URL]').slice(0,300),Date.now()).run();}catch(e){if(!(e instanceof HttpError&&e.status===429))console.error('Error event persistence failed');}}
export async function respondError(e:any,jobId?:string){const status=e instanceof HttpError?e.status:400;if(status!==429)await event(status>=500?'server_error':'request_rejected',e.message||'Request failed',jobId);return Response.json({error:e.message||'Request failed',retryable:status>=500||status===429},{status,headers:{'Cache-Control':'no-store',...(e.retryAfter?{'Retry-After':String(e.retryAfter)}:{})}});}
export async function workerAuth(request:Request){const supplied=request.headers.get('authorization')||'',expected=process.env.PARCEL_WORKER_SECRET;if(!expected||!await equal(supplied,'Bearer '+expected))throw new HttpError(403,'Worker authorization required.');}
async function equal(a:string,b:string){return await hash(a)===await hash(b);}
