import {claimCheckout,submitCheckout,recordPayment} from './checkout-state';
import {saveNotification} from './notifications';
import {paypalCheckout,confirmPayPal} from './paypal';
import {downloadLink} from './capabilities';
import {paymentsReady,stripeReady} from './launch';
import {db,bucket,hash,client,rate,HttpError,event} from './guard';
import {checked,stripe} from './server';
import {filename} from './export.mjs';
export const RETENTION=24*3600000;
export async function getJob(request:Request,id:string){if(!/^[a-f0-9-]{36}$/.test(id))throw new HttpError(404,'Export not found.');const job:any=await db().prepare('SELECT * FROM exports WHERE id=?').bind(id).first();if(!job||await hash(request.headers.get('x-export-key')||'')!==job.key_hash)throw new HttpError(404,'Export not found. Use the original recovery link.');if(job.expires<Date.now()||job.state==='expired')throw new HttpError(410,'This export expired. Files are retained for 24 hours.');return job;}
export async function createJob(request:Request,body:any){const j=await checked(body);if(j.amount&&!paymentsReady())throw new HttpError(503,'Paid exports are not enabled yet. Export up to 25 products for free.');const ip=await client(request);if(!/^[a-f0-9-]{36}$/.test(body.attempt||'')||typeof body.key!=='string'||body.key.length!==64)throw new HttpError(400,'Export recovery key required.');const idem=await hash(body.key+':'+body.attempt);const existing:any=await db().prepare('SELECT * FROM exports WHERE idempotency=?').bind(idem).first();if(existing){if(existing.expires<=Date.now()||existing.state==='expired')throw new HttpError(410,'This export attempt expired. Start a new export.');if(existing.key_hash!==await hash(body.key)||existing.hash!==j.hash)throw new HttpError(409,'That export attempt has different contents.');return existing;}
 await rate(request,'create-export',5,86400000);await rate(request,'create-burst',3,60000);
 const active:any=await db().prepare("SELECT COUNT(*) n FROM exports WHERE ip=? AND state IN ('awaiting_payment','queued','downloading','packing') AND expires>?").bind(ip,Date.now()).first();if(active.n>=2)throw new HttpError(429,'Two exports are already active. Finish or cancel one first.',60);
 const global:any=await db().prepare("SELECT COUNT(*) n FROM exports WHERE state IN ('queued','downloading','packing') AND expires>?").bind(Date.now()).first();if(global.n>=10)throw new HttpError(429,'The export queue is full. Try again shortly.',60);
 const metadata=body.items.map((i:any)=>({handle:i.handle,url:i.url,title:String(i.title||i.handle).slice(0,255),sku:String(i.sku||'').slice(0,255),position:Number(i.position)||0,alt:String(i.alt||'').slice(0,512)}));
 const options={mode:['sku','original','handle'].includes(body.options?.mode)?body.options.mode:'sku',folders:body.options?.folders!==false,manifest:body.options?.manifest!==false};
 const used=new Set(),counts=new Map();const items=metadata.map((i:any)=>{const n=(counts.get(i.handle)||0)+1;counts.set(i.handle,n);return {...i,filename:filename(i,n,options.mode,options.folders,used,'image'),index:n};});
 const id=crypto.randomUUID(),now=Date.now(),manifest='exports/'+id+'/manifest.json';await saveNotification(id,body.email,body.key);
 try{await bucket().put(manifest,JSON.stringify({items,options}),{httpMetadata:{contentType:'application/json'}});const inserted=await db().prepare("INSERT INTO exports(id,key_hash,owner,ip,hash,manifest,state,total,max_bytes,amount,next_run,created,expires,idempotency) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM exports WHERE ip=? AND state IN ('awaiting_payment','queued','downloading','packing') AND expires>?)<2 AND (SELECT COUNT(*) FROM exports WHERE state IN ('awaiting_payment','queued','downloading','packing') AND expires>?)<10").bind(id,await hash(body.key),ip,ip,j.hash,manifest,'queued',items.length,j.amount?1000000000:300000000,j.amount,now,now,now+RETENTION,idem,ip,now,now).run();if(!inserted.meta.changes)throw new HttpError(429,'The active-export limit has been reached.',60);}catch(e){await bucket().delete(manifest);await db().prepare('DELETE FROM email_outbox WHERE job_id=?').bind(id).run();throw e;}
 return db().prepare('SELECT * FROM exports WHERE id=?').bind(id).first();}
export async function checkoutJob(job:any,origin:string,recoverForCancellation=false){if(!recoverForCancellation&&!['complete','partial'].includes(job.state)||recoverForCancellation&&!['awaiting_payment','complete','partial'].includes(job.state))throw new HttpError(409,'This export is not awaiting payment.');if(!job.amount)return {free:true};if(job.payment_intent)return {paid:true};if((job.session||job.checkout_started)&&job.payment_provider!=='stripe')throw new HttpError(409,'Continue the existing PayPal checkout.');if(job.session){const s=await stripe('checkout/sessions/'+job.session);if(s.payment_status==='paid'){await confirmPayment(job);return {paid:true};}if(!recoverForCancellation&&!stripeReady())throw new HttpError(503,'Paid checkout is currently unavailable.');if(s.status==='open'&&s.url)return {url:s.url};throw new HttpError(409,'Checkout expired. Start a new export.');}
 if(!recoverForCancellation&&!stripeReady())throw new HttpError(503,'Paid checkout is currently unavailable.');if(!job.checkout_started&&job.expires<Date.now()+1800000)throw new HttpError(409,'This export expires too soon for checkout. Start a new export.');const p=new URLSearchParams({mode:'payment',expires_at:String(Math.floor(job.expires/1000)),success_url:origin+'/results?export='+job.id+'&session_id={CHECKOUT_SESSION_ID}',cancel_url:origin+'/results?export='+job.id+'&cancelled=1','line_items[0][price_data][currency]':'usd','line_items[0][price_data][unit_amount]':String(job.amount),'line_items[0][price_data][product_data][name]':'Parcel image export','line_items[0][quantity]':'1','metadata[job_hash]':job.hash,'metadata[export_id]':job.id});job=await claimCheckout(job,'stripe',p.toString());const s=await submitCheckout(job,(payload,key)=>stripe('checkout/sessions',new URLSearchParams(payload),key));return {url:s.url};}
export async function confirmPayment(job:any){if(job.payment_provider==='paypal')return confirmPayPal(job);if(!job.session)return false;const s=await stripe('checkout/sessions/'+job.session);if(s.payment_status!=='paid')return false;if(s.metadata?.job_hash!==job.hash||s.metadata?.export_id!==job.id||s.amount_total!==job.amount||s.currency!=='usd'||!s.payment_intent)throw new HttpError(409,'Payment does not match this export.');await recordPayment(job,typeof s.payment_intent==='string'?s.payment_intent:s.payment_intent.id);return true;}
export async function status(job:any){const notification:any=await db().prepare('SELECT state FROM email_outbox WHERE job_id=?').bind(job.id).first();const ahead:any=await db().prepare("SELECT COUNT(*) n,COALESCE(SUM(MAX(0,total-cursor)),0) images FROM exports WHERE state IN ('queued','downloading','packing') AND expires>? AND id!=?").bind(Date.now(),job.id).first();const remaining=Math.max(0,job.total-job.cursor);const etaSeconds=['queued','downloading','packing'].includes(job.state)?Math.ceil((remaining+ahead.images/2)*3/2)+60+Math.ceil(Math.max(job.bytes,remaining*1000000)/20000000)*5:null;const parts=await db().prepare('SELECT part,bytes,images FROM export_parts WHERE job_id=? ORDER BY part').bind(job.id).all();const errors=await db().prepare("SELECT position,error FROM export_images WHERE job_id=? AND status='failed' LIMIT 20").bind(job.id).all();return {etaSeconds,etaApproximate:true,queueJobs:ahead.n,readyAt:job.ready_at,emailState:notification?.state||null,paymentProvider:job.session||job.checkout_started?job.payment_provider:null,id:job.id,state:job.state,total:job.total,completed:job.completed,failed:job.failed,bytes:job.bytes,parts:parts.results.length?[{part:1,bytes:parts.results.reduce((n:number,p:any)=>n+p.bytes,0),images:job.completed}]:[],expires:job.expires,lastError:job.last_error,refundState:job.refund_state,paid:!!job.payment_intent,amount:job.amount,retries:job.retry_count,reviewId:job.review_id,errors:errors.results};}
export async function jobAction(request:Request,job:any,action:string,details:any={}){await rate(request,'job-action',120);const lease=crypto.randomUUID(),now=Date.now();const current:any=await db().prepare('UPDATE exports SET lease_owner=?,lease_until=? WHERE id=? AND lease_until<? AND expires>? RETURNING *').bind(lease,now+120000,job.id,now,now).first();if(!current)throw new HttpError(409,'This export is currently processing. Try the action again shortly.',5);try{return await performAction(request,current,action,details);}finally{await db().prepare('UPDATE exports SET lease_owner=NULL,lease_until=0 WHERE id=? AND lease_owner=?').bind(job.id,lease).run();}}
async function performAction(request:Request,job:any,action:string,details:any){if(action==='download'){
 if(job.parts>1){const checkpoint=await bucket().head('exports/'+job.id+'/zip-state/'+job.parts+'.json');if(!checkpoint){await db().prepare('DELETE FROM export_parts WHERE job_id=?').bind(job.id).run();await db().prepare("UPDATE exports SET state='packing',parts=0,pack_cursor=0,next_run=? WHERE id=?").bind(Date.now(),job.id).run();return {preparing:true};}}
 return downloadLink(job,1,new URL(request.url).origin);
 }if(action==='checkout'){if(job.payment_intent)return {paid:true};if(!['complete','partial'].includes(job.state))throw new HttpError(409,'Wait until your package is ready before paying.');if(details.provider==='paypal'||job.payment_provider==='paypal'&&(job.session||job.checkout_started))return paypalCheckout(job,new URL(request.url).origin);return checkoutJob(job,new URL(request.url).origin);}if(action==='confirm'){await confirmPayment(job);return {ok:true};}
 if(action==='cancel'){if(job.state==='awaiting_payment'&&job.amount&&!job.session){await checkoutJob(job,new URL(request.url).origin,true);job=await db().prepare('SELECT * FROM exports WHERE id=?').bind(job.id).first();}if(job.state==='awaiting_payment'&&job.session&&job.payment_provider==='stripe'){const checkout=await stripe('checkout/sessions/'+job.session);if(checkout.payment_status==='paid'){await confirmPayment(job);}else if(checkout.status==='open'){await stripe('checkout/sessions/'+job.session+'/expire',new URLSearchParams());}}await db().prepare("UPDATE exports SET state='cancelled',lease_until=0,lease_owner=NULL,refund_state=CASE WHEN payment_intent IS NOT NULL AND completed=0 THEN 'pending' ELSE refund_state END WHERE id=? AND state IN ('awaiting_payment','queued','downloading','packing')").bind(job.id).run();return {ok:true};}
 if(action==='retry'){if(!['failed','partial'].includes(job.state)||job.refund_state||job.retry_count>=2||(job.session||job.checkout_started)&&!job.payment_intent)throw new HttpError(409,'This export cannot be retried. Request a review instead.');await db().batch([db().prepare("DELETE FROM export_images WHERE job_id=? AND status='failed'").bind(job.id),db().prepare('DELETE FROM export_parts WHERE job_id=?').bind(job.id),db().prepare("UPDATE exports SET state='queued',cursor=0,pack_cursor=0,parts=0,failed=0,attempts=0,retry_count=retry_count+1,next_run=?,last_error=NULL WHERE id=? AND state IN ('failed','partial') AND refund_state IS NULL AND retry_count<2").bind(Date.now(),job.id)]);return {ok:true};}
 if(action==='refund'){if(!job.payment_intent||!['failed','cancelled'].includes(job.state)||job.completed>0)throw new HttpError(409,'Automatic refunds are available when a paid export delivers no images. For partial exports, request a review.');await db().prepare("UPDATE exports SET refund_state='pending',next_run=? WHERE id=? AND refund_state IS NULL").bind(Date.now(),job.id).run();return {ok:true};}
 if(action==='review'){if(!job.payment_intent)throw new HttpError(409,'Reviews are available for paid exports.');const review=job.review_id||'case-'+crypto.randomUUID();await db().prepare('UPDATE exports SET review_id=?,review_resolved_at=NULL WHERE id=?').bind(review,job.id).run();await event('paid_export_review','Customer requested review',job.id);return {reviewId:review};}throw new HttpError(400,'Unknown export action.');}
