import {integer,sqliteTable,text,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const exportsTable=sqliteTable('exports',{
 checkoutPayload:text('checkout_payload'),checkoutStarted:integer('checkout_started'),checkoutReview:integer('checkout_review').notNull().default(0),reviewResolvedAt:integer('review_resolved_at'),emailReviewedAt:integer('email_reviewed_at'),
 readyAt:integer('ready_at'),paymentProvider:text('payment_provider').notNull().default('stripe'),id:text('id').primaryKey(),keyHash:text('key_hash').notNull(),owner:text('owner').notNull(),ip:text('ip').notNull(),hash:text('hash').notNull(),manifest:text('manifest').notNull(),state:text('state').notNull(),total:integer('total').notNull(),cursor:integer('cursor').notNull().default(0),packCursor:integer('pack_cursor').notNull().default(0),completed:integer('completed').notNull().default(0),failed:integer('failed').notNull().default(0),bytes:integer('bytes').notNull().default(0),maxBytes:integer('max_bytes').notNull(),parts:integer('parts').notNull().default(0),amount:integer('amount').notNull(),session:text('session'),paymentIntent:text('payment_intent'),refundState:text('refund_state'),refundId:text('refund_id'),retryCount:integer('retry_count').notNull().default(0),attempts:integer('attempts').notNull().default(0),nextRun:integer('next_run').notNull(),leaseUntil:integer('lease_until').notNull().default(0),leaseOwner:text('lease_owner'),created:integer('created').notNull(),expires:integer('expires').notNull(),lastError:text('last_error'),reviewId:text('review_id'),idempotency:text('idempotency').notNull().unique(),
 // Agency plan (see docs/agency-runbook.md): agency_id links an export to its agency account, priority orders the worker queue (0 normal, 1 agency), client_name renames the ZIP; usage_slot=1 while the export holds one of the account's 50 monthly slots (usage_period says which period), released on cancel-before-start or zero-image failure.
 agencyId:text('agency_id'),priority:integer('priority').notNull().default(0),clientName:text('client_name'),usageSlot:integer('usage_slot').notNull().default(0),usagePeriod:integer('usage_period'),
},t=>[index('exports_due').on(t.state,t.nextRun,t.leaseUntil),index('exports_owner').on(t.owner,t.created),index('exports_agency').on(t.agencyId,t.created)]);
export const exportImages=sqliteTable('export_images',{id:text('id').primaryKey(),jobId:text('job_id').notNull(),position:integer('position').notNull(),objectKey:text('object_key'),status:text('status').notNull(),bytes:integer('bytes').notNull().default(0),error:text('error'),crc:integer('crc'),extension:text('extension')},t=>[index('export_images_job').on(t.jobId,t.position)]);
export const exportParts=sqliteTable('export_parts',{id:text('id').primaryKey(),jobId:text('job_id').notNull(),part:integer('part').notNull(),objectKey:text('object_key').notNull(),bytes:integer('bytes').notNull(),images:integer('images').notNull()},t=>[index('export_parts_job').on(t.jobId,t.part)]);
export const usage=sqliteTable('usage_limits',{id:text('id').primaryKey(),value:integer('value').notNull().default(0),expires:integer('expires').notNull()});
export const errors=sqliteTable('error_events',{id:text('id').primaryKey(),jobId:text('job_id'),code:text('code').notNull(),detail:text('detail').notNull(),created:integer('created').notNull()},t=>[index('error_events_created').on(t.created)]);
export const workerHealth=sqliteTable('worker_health',{id:text('id').primaryKey(),seen:integer('seen').notNull(),version:text('version').notNull()});

export const emailOutbox=sqliteTable('email_outbox',{jobId:text('job_id').primaryKey(),payload:text('payload'),message:text('message'),state:text('state').notNull(),providerId:text('provider_id'),attempts:integer('attempts').notNull().default(0),nextRun:integer('next_run').notNull(),leaseUntil:integer('lease_until').notNull().default(0),leaseOwner:text('lease_owner')});

// Agency subscription plan ($49/month, invite-only beta). Accounts are identified by a private
// agency key (stored only as a SHA-256 hash, like export recovery keys). status: pending (checkout
// started), active, past_due, free (cancelled or period ended). cancel_at_period_end mirrors Stripe so the
// account page can say "cancels on …". suspended=1 blocks the account regardless of status (disputes, abuse).
export const agencyAccounts=sqliteTable('agency_accounts',{id:text('id').primaryKey(),keyHash:text('key_hash').notNull().unique(),email:text('email'),stripeCustomer:text('stripe_customer'),stripeSubscription:text('stripe_subscription'),stripeSession:text('stripe_session'),status:text('status').notNull().default('pending'),periodStart:integer('period_start'),periodEnd:integer('period_end'),statusCheckedAt:integer('status_checked_at'),cancelAtPeriodEnd:integer('cancel_at_period_end').notNull().default(0),suspended:integer('suspended').notNull().default(0),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('agency_accounts_status').on(t.status,t.statusCheckedAt)]);
// Single-use invite codes for the beta gate. account_id/used_at are set when a code is redeemed.
export const inviteCodes=sqliteTable('invite_codes',{code:text('code').primaryKey(),accountId:text('account_id'),usedAt:integer('used_at'),created:integer('created').notNull()});
// Exports used per billing period, keyed to the Stripe period start. Slots are reserved atomically at creation and given back on cancel-before-start or zero-image failure.
export const usageCycles=sqliteTable('usage_cycles',{accountId:text('account_id').notNull(),periodStart:integer('period_start').notNull(),used:integer('used').notNull().default(0)},t=>[primaryKey({columns:[t.accountId,t.periodStart]})]);
